### ISSUE TITLE
Fix for array and object initialization

### ISSUE THREAD

**Issue by madskristensen** [MackMendes/JsAdvice-Beta#1]
How about adding fixes for object and array initializers? More here https://addyosmani.com/blog/fixmyjs/

The idea is that `new Array()` is replaced by `[]` and `new Object()` is replaced by `{}`

**Comment by MackMendes** [comment]
Hello Mads! What an honor! I saw your presentation on "Build" this year, helped me a lot in this project! I still have to refactor some points! Rush to deliver this version beta, for the masters course discipline.

And I'm very happy for the Issues! Certainly will be created! Feel free to create more and want to collaborate, it would be a great honor!

Kind regards.

Ps. Sorry for the english...

**Comment by madskristensen** [comment]
Here's some more inspiration for light bulb suggestions https://github.com/jshint/fixmyjs

**Comment by MackMendes** [comment]
Show Mads! It has plenty of features (fix)! After the master's evidence, grow further this project and implement these features!

**Comment by MackMendes** [comment]
Thanks Mads! And welcome to create new issues!
