### ISSUE TITLE
Extension marked as "Trial" instead of "Free" on the Gallery

### ISSUE THREAD

**Issue by madskristensen** [MackMendes/JsAdvice-Beta#3]
I don't know if it was on purpose, but the extension is marked as being a trial.

![image](https://cloud.githubusercontent.com/assets/1258877/16163032/ecc1901e-348b-11e6-8672-5153d5da0cbd.png)

If it is on purpose, then it might be a good idea to describe how to obtain a full version/license etc.

**Comment by MackMendes** [comment]
Hi Mads, so I put as 'trial' on purpose to present this project to a discipline on my master's degree. But, week next move to 'free'! 

In the future, I am thinking in include a Machine Learning with Artificial Intelligence techniques, to learn the developer level for, gradually teach the JavaScript language and JS Frameworks, suggesting with best practices.

**Comment by MackMendes** [comment]
Changed to free! :tada:

**Comment by MackMendes** [comment]
Thanks Mads!
